### ISSUE TITLE
[Suggestion] Changing Splitters to Vanilla Drops

### ISSUE THREAD

**Issue by cymophic** [TeamMidnightDust/ThisRocks#33]
Maybe instead of cobblestone splitters, the rocks could drop varied loot such as either nothing (meaning that the rock's unusable), flint, or a whole cobblestone instead. I find the current textures of the splitters a bit distasteful, though I know that the team would change it in the future. Still, I love the mod nonetheless since it makes the world more alive compared to the bland vanilla look. Looking forward to more updates!

**Comment by Motschen** [comment]
I actually like the current system with the splitters (that's why I implemented it). You can customize the drops via datapacks, your suggestions would be fairly easy to implement that way.
The splitters are actually a model that uses the vanilla textures of the respective block and I have no plans on changing it, as I think it fits in perfectly and looks nice imo.
