### ISSUE TITLE
Feature RQ: Config options

### ISSUE THREAD

**Issue by Zentheon** [TeamMidnightDust/ThisRocks#8]
Hi! I enjoy this mod quite a bit but do have one issue in that nothing about the generation is customizeable. Blacklisting dimensions is one thing, as well as perhaps being able to adjust the rates of specific types and their sizes. Personally I wouldn't mind if this was either nice fancy modmenu integration or simply datapack compat, just keeping the rockin' rocks from generating in unfitting modded dimensions

**Comment by Muffintiem** [comment]
I personally would like to be able to disable this in modded biomes in the Nether but not the Overworld. Because the mod I use to add biomes to the Nether already adds lots of little stuff to the ground of its own biomes but not the Vanilla ones so this mod makes them all equally interesting. Meanwhile it helps all of the overworld so I wouldn't want to turn it off entirely from modded biomes.
